"""Render verified results into the existing Q123 page; deterministic and idempotent."""
from html import escape
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
def pct(v): return f'{v*100:+.2f}%'
def num(v): return f'{v:.3f}'
def money(v): return f'{v/100_000_000:.2f}억'
def table(headers, rows):
    return '<div style="overflow-x:auto"><table class="data-table"><thead><tr>'+''.join(f'<th>{escape(x)}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{escape(str(v))}</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def panel(title, body): return f'<div class="panel mb-24"><div class="panel-title">{title}</div>{body}</div>'
def group(key, title, body):
    c='' if key=='A' else ' collapsed'
    return f'<div class="group-header{c}" data-group="{key}" onclick="toggleGroup(this)"><div class="label">{key}</div><div class="title">{title}</div><div class="chevron">▾</div></div><div class="group-body{c}">{body}</div>'

def render():
    r=json.loads((ROOT/'docs/q123_results.json').read_text()); q=r['benchmark']['Q123']
    html=(ROOT/'docs/q123.html').read_text()
    perf='<section class="tab-panel" id="performance">\n<!-- Generated by scripts/render_q123.py -->'
    perf += '<div class="perf-summary"><div class="head">PRICE RETURN · 독립 재현 결과</div><div class="toggle-all" onclick="toggleAllGroups()">전체 펼치기</div><p>2010-02-11 ~ 2026-05-15 · 2010년 및 2011~2021년 첫 거래일, 12개 시작 시점의 산술평균 · 최초 1억 · 추가납입 없음 · 편도 5bps.</p><p>업로드 Investing CSV의 분할 반영 OHLC 가격 기준. 배당·환율 미반영. 기존 40.86%는 다른 데이터·가정으로 산출된 수치이므로 이번 검증값과 직접 비교하지 않습니다. 배당 재투자 성과는 원본 자료 확보 후 별도 검증합니다.</p></div>'
    rows=[]
    for t in ['Q123','QLD','QQQ','SPY','TQQQ']:
        m=r['benchmark'][t]; rows.append([t,pct(m['cagr']),pct(m['mdd']),num(m['calmar']),money(m['final'])])
    a=panel('BENCHMARK · 동일 가격수익 기준',table(['전략','평균 CAGR','평균 MDD','평균 Calmar','평균 최종평가액'],rows))
    a+=panel('START YEAR · 시작 시점별 결과',table(['실제 시작일','CAGR','MDD','Calmar','전환 수'],[[s['start'],pct(s['cagr']),pct(s['mdd']),num(s['calmar']),s['transitions']] for s in r['scenarios']]))
    a+=panel('COST · 편도 비용 민감도',table(['비용','CAGR','평균 MDD','최악 MDD','Calmar','최종평가액','주문 수','전환 수'],[[b+'bps',pct(m['cagr']),pct(m['mdd']),pct(m['worst_mdd']),num(m['calmar']),money(m['final']),f"{m['orders']:.2f}",f"{m['transitions']:.2f}"] for b,m in r['costs'].items()])+'<p>주문 수 = 최초 매수 1 + 모드전환당 매도·매수 2. 종료일 평가만 하며 강제 청산 주문은 포함하지 않습니다. 각 시나리오 Calmar를 계산한 뒤 평균하므로 평균 CAGR ÷ 평균 MDD와 다를 수 있습니다.</p>')
    perf+=group('A','핵심 성과',a)
    wrows=[]
    for i,w in enumerate(r['windows'],1):
        t,o=w['train'],w['oos'];wrows.append([f'W{i}',t['start']+' ~ '+t['end'],o['start']+' ~ '+o['end'],pct(t['cagr']),num(t['calmar']),pct(o['cagr']),pct(o['mdd']),num(o['calmar'])])
    b=panel('기간 분할 검증 · 고정 규칙',table(['구간','앞 구간','뒤 구간','앞 CAGR','앞 Calmar','뒤 CAGR','뒤 MDD','뒤 Calmar'],wrows)+'<p>각 구간은 NORMAL에서 새로 시작하고 지표는 이전 200거래일 이상으로 워밍업합니다. 현재 확정 규칙을 과거 여러 구간에 적용한 검증입니다. 과거 시점에서 파라미터를 선택한 진정한 워크포워드 검증이 아니므로 이 결과만으로 과최적화가 없다고 판단할 수 없습니다.</p>')
    b+=panel('PARAMETER · 7개 설정',table(['설정','CAGR','MDD','Calmar'],[[k,pct(v['cagr']),pct(v['mdd']),num(v['calmar'])] for k,v in r['sensitivity'].items()]))
    bt=r['bootstrap']; b+=panel('BOOTSTRAP · 실현 전략 수익률 블록 재조합',table(['평균 CAGR','평균 MDD','평균 Calmar','CAGR ≥ 15% 비율','MDD < -65% 비율'],[[pct(bt['cagr']),pct(bt['mdd']),num(bt['calmar']),f"{bt['p_cagr_15']*100:.1f}%",f"{bt['p_mdd_65']*100:.1f}%"]])+'<p>2010 시작의 일별 실현 전략 수익률 · 원형 21거래일 블록 · 복원추출 500회 · seed 20261006. 재조합된 시장 경로에서 신호를 다시 계산한 결과가 아닙니다. 이 비율은 미래 성공확률을 뜻하지 않습니다.</p>')
    b+=panel('추가 검증 상태','<p>기존 레짐 전환·충격 테스트는 생성 산식과 코드가 없어 이번 정본에서 확정값으로 사용하지 않습니다. 2000~2009 닷컴버블·금융위기 스트레스는 아직 검증하지 않았습니다.</p>')
    perf+=group('B','기간·민감도·Bootstrap 검증',b)
    c=panel('TAX · 외부 납부 가정 분리',table(['항목','12개 평균'],[['세금 미차감 계좌평가액',money(q['final'])],['누적 발생 예상세금',money(q['tax_liability'])],['평가액 − 누적 예상세금',money(q['net'])],['동일 경제적 순자산의 환산 CAGR',pct(q['net_cagr'])],['종료일 전량 청산·비용·예상세금 반영 순자산',money(q['liquid_net'])]])+'<p>연간 실현손익 합산 후 250만원을 공제하고 양수 부분에 22%를 적용한 단순 시뮬레이션입니다. 환율은 고정으로 두며 납부 이력·신고액이 아닙니다. 세금을 투자계좌에서 차감하지 않아 외부 자금 부담이 남습니다. 외부 납부 현금흐름을 반영한 XIRR과도 다릅니다. 마지막 보유분 청산은 해당 연도의 기존 손익·공제와 함께 재계산합니다.</p><p>세금 인출 모델의 기존 31.52%와 외부 납부 모델을 혼용하지 않습니다. 경제적 CAGR은 각 시나리오에서 별도로 계산한 뒤 평균합니다.</p>')
    perf+=group('C','세금·경제적 순자산',c)
    removed=sum(len(a['removed_non_sessions']) for a in r['data_audit'].values())
    d=panel('검증 범위와 데이터','<p>미국 NYSE 거래 캘린더로 비거래일 '+str(removed)+'행을 제거했습니다. 누락·중복 거래일과 0 이하 가격은 오류 처리하고 보간하지 않습니다. QQQ 지표에는 2008~2009 원시 종가를 워밍업으로 추가합니다. 초기 보유는 NORMAL이며 BOOST peak는 실제 진입일 종가부터 추적합니다.</p><p>ETF 초기 가격이 센트 단위로 반올림된 업로드 자료이므로 초기 레버리지 ETF 수익률에 정밀도 한계가 있습니다. 운용보수·레버리지 조달비용은 ETF 가격에 반영된 부분을 추가로 이중 차감하지 않습니다.</p><p><a href="./q123_results.json">전체 계산 결과 JSON</a> · <a href="./q123_transitions.csv">전체 신호일·체결일 CSV</a> · <a href="https://github.com/baekhamo-beep/investment-dashboard/blob/main/docs/Q123_METHOD.md">규칙·산식</a></p>')
    perf+=group('D','산식·자료와 검증 한계',d)+'</section>\n'
    html=re.sub(r'<section class="tab-panel" id="performance">.*?</section>\n*',lambda _:perf.replace('><','>\n<').rstrip()+'\n\n',html,flags=re.S)
    risk='<section class="tab-panel" id="risk">'+panel('Q123 위험과 검증 범위','<p>BEAR도 QQQ를 보유하므로 하락을 차단하지 않습니다. TQQQ·QLD의 일별 레버리지와 변동성 누적으로 큰 손실이 발생할 수 있습니다.</p><p>현재 가격수익 검증의 평균 MDD는 '+pct(q['mdd'])+'이며 미래 손실 한도가 아닙니다. 2010년 이후 결과에 닷컴버블과 2008 금융위기가 포함되지 않습니다.</p><p>신호는 완료된 거래일 종가로 확정하고 다음 거래일 시가에서 실행합니다. 급격한 갭 하락, 주문 지연과 실제 슬리피지는 편도 정률 비용으로 충분히 설명되지 않습니다.</p><p>전환 때마다 실현손익이 발생하므로 실제 손익·환율과 신고내역을 별도로 관리해야 합니다. 세금 외부 납부 모델은 계좌 복리를 유지하지만 추가 외부 자금이 필요합니다.</p><p>기존 회복기간·포트폴리오 전체 MDD·연 7% 세금 예비비·레짐 확률 등 원본 산식이 없는 추정치는 이번 정본에서 제거했습니다.</p>')+'</section>'
    html=re.sub(r'<section class="tab-panel" id="risk">.*?</section>',lambda _:risk,html,flags=re.S)
    recent=[e for e in r['events'] if '2025-03-06'<=e['signal_date']<=r['method']['end']]
    sidebar=panel('TRANSITIONS · 2025-03-06 ~ 2026-05-15',f'<p><b>{len(recent)}회 전환</b> · 2025년 한 해 6회. 뉴스 설명 대신 가격 조건을 근거로 기록합니다.</p>'+table(['전환','12개 시작 평균'],[[k,f'{v:.2f}'] for k,v in r['transition_means'].items()])+'<p>전환 횟수만으로 세금액을 계산할 수 없습니다. 연간 실제 실현손익이 필요합니다.</p>')
    start=html.index('    <div class="panel accent">\n      <div class="panel-title">TRANSITIONS') if '    <div class="panel accent">\n      <div class="panel-title">TRANSITIONS' in html else html.index('<!-- Q123_TRANSITION_SUMMARY_START -->')
    if '<!-- Q123_TRANSITION_SUMMARY_START -->' in html:
        end=html.index('<!-- Q123_TRANSITION_SUMMARY_END -->',start)+len('<!-- Q123_TRANSITION_SUMMARY_END -->')
    else:
        end=html.index('\n  </div>\n\n  <!-- ─── 전환 로그 사례',start)
    html=html[:start]+'<!-- Q123_TRANSITION_SUMMARY_START -->'+sidebar+'<!-- Q123_TRANSITION_SUMMARY_END -->'+html[end:]
    case='<div class="section-label">CASE STUDY · 신호일과 실제 체결일</div>'+panel('2025-03-06 ~ 2026-05-15 · 8회',table(['신호일 D','체결일 D+1 시가','전환','근거'],[[e['signal_date'],e['execution_date'],e['from']+' → '+e['to'],e['reason']] for e in recent])+'<p>2025-06-24는 BEAR → BOOST 직행 신호입니다. 2026-04-08은 회복 첫날이며 5거래일 완료일은 4/14, 체결일은 4/15입니다. 5/15 기준 사례와 현재 상태를 구분합니다.</p>')
    later=[e for e in r['events'] if e['signal_date']>r['method']['end']]
    case+=panel('검증기간 이후 전환',table(['신호일','체결일','전환','근거'],[[e['signal_date'],e['execution_date'],e['from']+' → '+e['to'],e['reason']] for e in later]))
    marker='<div class="ascii-divider">─────────── ─── ── ─ TRANSITION CASE STUDY'
    start=html.index(marker); end=html.index('</section>',start)
    html=html[:start]+marker+' ─ ── ─── ───────────</div>\n'+case+'\n'+html[end:]
    # Headline numbers always come from the same generated scenario metrics.
    html=re.sub(r'가격수익 CAGR <span class="amber">[0-9.]+%</span>',lambda _:f'가격수익 CAGR <span class="amber">{q["cagr"]*100:.2f}%</span>',html)
    html=re.sub(r'가격수익 MDD <span class="down">-[0-9.]+%</span>',lambda _:f'가격수익 MDD <span class="down">{pct(q["mdd"])}</span>',html)
    html=re.sub(r'<span>Calmar [0-9.]+</span>',lambda _:f'<span>Calmar {num(q["calmar"])}</span>',html)
    html=re.sub(r'가격수익 CAGR <b style="color:var\(--amber\)">.*?배당 제외',lambda _:f'가격수익 CAGR <b style="color:var(--amber)">{pct(q["cagr"])}</b> · MDD <b style="color:var(--red)">{pct(q["mdd"])}</b> · Calmar <b>{num(q["calmar"])}</b> · 12개 시작 평균 · 배당 제외',html)
    html=html.replace('세후 CAGR <span class="amber">31.52%</span>',f'가격수익 CAGR <span class="amber">{q["cagr"]*100:.2f}%</span>')
    html=re.sub(r'세후 CAGR <b style="color:var\(--amber\)">\+31\.52%</b>.*?12개 시작 시나리오',f'가격수익 CAGR <b style="color:var(--amber)">{pct(q["cagr"])}</b> · MDD <b style="color:var(--red)">{pct(q["mdd"])}</b> · Calmar <b>{num(q["calmar"])}</b> · 12개 시작 평균 · 배당 제외',html)
    html=html.replace('백테스트 결과(CAGR +31.52%)','동일 규칙 백테스트 결과')
    html=html.replace('기준 자료: 세후 백테스트 v1 · Future Validation v1','기준 자료: Q123_CANONICAL_V2 · 업로드 가격수익 검증 · 편도 5bps')
    html=html.replace('② BOOST peak 대비 <b>-8%</b>', '② 진입일 이후 QQQ <b>종가 최고점</b> 대비 <b>-8%</b>')
    html=html.replace('BOOST 종료 후 21거래일 강제 휴식','종료 체결일 E 다음 E+1~E+21 거래일 동안 TQQQ 보유 금지. E+21 종가부터 신호 가능, E+22 시가부터 재진입 가능.')
    if '<!-- Q123_CANONICAL_NOTE -->' not in html:
        note=panel('Q123_CANONICAL_V2 · 실행 정의','<p>BEAR 진입이 최우선이며 BOOST → BEAR도 쿨다운을 시작합니다. 종가 = SMA200은 신규 BEAR 조건이 아니지만 회복 연속일을 충족하지 않습니다. BOOST 진입일을 보유 1일로 세며 63번째 종가에서 종료 신호를 내고 64번째 시가에 매도합니다. 종가 peak는 진입일 종가부터 계산합니다. 장중 가격으로 상태를 전환하지 않습니다.</p>')
        html=html.replace('<section class="tab-panel" id="rules">','<section class="tab-panel" id="rules">\n<!-- Q123_CANONICAL_NOTE -->'+note)
    (ROOT/'docs/q123.html').write_text(html)

if __name__=='__main__':render()
